version: '3.8'

services:
  weight-tracker:
    build: .
    container_name: weight-tracker-app
    restart: unless-stopped
    ports:
      - "3135:3000"
    volumes:
      - weight-tracker-data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - weight-tracker-network

networks:
  weight-tracker-network:
    driver: bridge

volumes:
  weight-tracker-data:
    driver: local